### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by epe** [maxammann/trello-to-deck#18]
Not sure if that has already been posted. I get this error when trying to import a board that had a background image set.

Traceback (most recent call last):
  File "./bin/trello-to-deck/scripts/trello-to-deck", line 37, in <module>
    json.loads(json_string, object_hook=lambda d: SimpleNamespace(**d))
  File "/home/user/.local/lib/python3.7/site-packages/trello_to_deck/trello.py", line 160, in to_board
    background_color = color_map[trello_json.prefs.background] if len(trello_json.prefs.background) != 24 else "green"
KeyError: 'grey'

**Comment by maxammann** [comment]
This should be fixed by https://github.com/maxammann/trello-to-deck/pull/15

Are you using the latest version on main/master?

**Comment by epe** [comment]
Yes i did a complete new download, cause I wasnt sure if my git fetch and git pull was succesful. Which one would be the correct command btw?

**Comment by maxammann** [comment]
`git pull`

the output you posted initially suggests that you are using an older version.

**Comment by epe** [comment]
> /bin/trello-to-deck$ git pull
> Bereits aktuell.
> 

offenbar doch noch ein bug?

**Comment by epe** [comment]
Another one with a different json file from trello: 

The response was: b'{"status":400,"message":"type must be provided"}'
Traceback (most recent call last):
  File "./bin/trello-to-deck/scripts/trello-to-deck", line 102, in <module>
    api.attachToCard(nextcloudBoardId, nextcloudStackId, nextcloudCardId, attachment.fileName, response.raw, attachment.mimeType)
  File "/home/user/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 146, in attachToCard
    {"file": (fileName, fileObject, mimeType)},
  File "/home/user/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 44, in postFiles
    response.raise_for_status()
  File "/home/user/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad request for url: https://net.net/index.php/apps/deck/api/v1.0/boards/25/stacks/73/cards/1084/attachments

**Comment by maxammann** [comment]
Hm seems like a separate issue, maybe deck changed their API in an unexpected way. Can you open a searate issue for that and post the initial error again?

Maybe also try to delete all .pyc files
