### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by epe** [maxammann/trello-to-deck#19]
Another one with a different json file from trello:

The response was: b'{"status":400,"message":"type must be provided"}'
Traceback (most recent call last):
File "./bin/trello-to-deck/scripts/trello-to-deck", line 102, in
api.attachToCard(nextcloudBoardId, nextcloudStackId, nextcloudCardId, attachment.fileName, response.raw, attachment.mimeType)
File "/home/user/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 146, in attachToCard
{"file": (fileName, fileObject, mimeType)},
File "/home/user/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 44, in postFiles
response.raise_for_status()
File "/home/user/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad request for url: https://net.net/index.php/apps/deck/api/v1.0/boards/25/stacks/73/cards/1084/attachments

**Comment by maxammann** [comment]
Thanks, I'll take a look on saturday :)

**Comment by maxammann** [comment]
Which deck version are you using? This is onyl tested with deck 1.10 and above

**Comment by maxammann** [comment]
I successfully imported this trello board with attachments: https://github.com/maxammann/trello-to-deck/blob/main/examples/kanban-template.json

**Comment by maxammann** [comment]
Closing this as there was no progress in the past 22 days.
