### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by nesnera** [maxammann/trello-to-deck#21]
```
$ trello-to-deck .. ..
Traceback (most recent call last):
  File "/usr/local/bin/trello-to-deck", line 6, in <module>
    from trello_to_deck.deck import DeckAPI
  File "/usr/local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 2, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by maxammann** [comment]
Thanks for the report! This seems like a bug. Probably some dependency is missing.

**Comment by maxammann** [comment]
I added the dependency
